# ./api-v1/api-doc.yml
swagger: '2.0'
basePath: '/v1'
info:
  title: 'A getting started API.'
  version: '1.0.0'
definitions:
  World:
    type: 'object'
    properties:
      name:
        description: 'The name of this world.'
        type: 'string'
    required:
      - 'name'
paths:
  /worlds:
    get:
      summary: 'Returns worlds by name.'
      operationId: 'getWorlds'
      parameters:
        - in: 'query'
          name: 'worldName'
          required: true
          type: 'string'
      responses:
        200:
          description: 'A list of worlds that match the requested name.'
          schema:
            type: 'array'
            items:
              $ref: '#/definitions/World'
        default:
          description: 'An error occurred'
          schema:
            additionalProperties: true
